server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC
    username: root
    password: 123456
  main:
    banner-mode: off
  resources:
    static-locations= file:F:\test\app\java\demo\src\main\resources\static\images
  mvc:
    view:
      suffix: html
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
#  configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
