web:
  upload-path: D:/data/

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC
    username: root
    password: 123456
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 100KB  # 文件上传大小的限制，设置最大值，不能超过，否则报错
      max-request-size: 2MB # 文件最大请求限制，用于批量

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
#  configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
